#!/usr/bin/env tsx
/**
 * Creates an ignored wrangler.toml for Cloudflare Workers Builds.
 * Build variables provide binding metadata; Worker Secrets remain in Cloudflare.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const GENERATED_CONFIG_MARKER = '# Generated by scripts/generate-wrangler-config.ts. Do not commit.';

export interface CloudflareBuildEnv {
  TYPECHO_CF_WORKER_NAME?: string;
  TYPECHO_CF_D1_DATABASE_ID?: string;
  TYPECHO_CF_D1_DATABASE_NAME?: string;
  TYPECHO_CF_R2_BUCKET_NAME?: string;
  TYPECHO_CF_KV_NAMESPACE_ID?: string;
  TYPECHO_CF_PBKDF2_ITERATIONS?: string;
}

export interface GeneratedConfigResult {
  path: string;
  created: boolean;
}

function required(env: CloudflareBuildEnv, name: keyof CloudflareBuildEnv): string {
  const value = env[name]?.trim();
  if (!value) throw new Error(`Missing Cloudflare build variable: ${name}`);
  return value;
}

function optional(env: CloudflareBuildEnv, name: keyof CloudflareBuildEnv, fallback: string): string {
  return env[name]?.trim() || fallback;
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function pbkdf2Iterations(env: CloudflareBuildEnv): string {
  const value = optional(env, 'TYPECHO_CF_PBKDF2_ITERATIONS', '50000');
  const parsed = Number(value);
  if (!Number.isInteger(parsed) || parsed < 50_000 || parsed > 600_000) {
    throw new Error('TYPECHO_CF_PBKDF2_ITERATIONS must be an integer between 50000 and 600000');
  }
  return String(parsed);
}

export function generateWranglerToml(env: CloudflareBuildEnv): string {
  const workerName = optional(env, 'TYPECHO_CF_WORKER_NAME', 'typecho-cf');
  const d1DatabaseId = required(env, 'TYPECHO_CF_D1_DATABASE_ID');
  const d1DatabaseName = required(env, 'TYPECHO_CF_D1_DATABASE_NAME');
  const r2BucketName = required(env, 'TYPECHO_CF_R2_BUCKET_NAME');
  const kvNamespaceId = env.TYPECHO_CF_KV_NAMESPACE_ID?.trim() || '';
  const iterations = pbkdf2Iterations(env);

  return `${GENERATED_CONFIG_MARKER}
# Binding metadata comes from Cloudflare build variables. Secrets are never written here.
name = ${tomlString(workerName)}
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2026-04-21"
compatibility_flags = [ "nodejs_compat" ]

[vars]
PBKDF2_ITERATIONS = ${tomlString(iterations)}

[assets]
directory = "dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = ${tomlString(d1DatabaseName)}
database_id = ${tomlString(d1DatabaseId)}
migrations_dir = "drizzle"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = ${tomlString(r2BucketName)}

${kvNamespaceId ? `[[kv_namespaces]]
binding = "TYPECHO_CACHE"
id = ${tomlString(kvNamespaceId)}

` : ''}[observability.logs]
enabled = true
invocation_logs = false
persist = false

[observability.traces]
enabled = false
`;
}

export function ensureCloudflareWranglerConfig(
  cwd: string,
  env: CloudflareBuildEnv,
): GeneratedConfigResult {
  const path = resolve(cwd, 'wrangler.toml');
  if (existsSync(path)) {
    const existing = readFileSync(path, 'utf-8');
    if (!existing.startsWith(GENERATED_CONFIG_MARKER)) {
      return { path, created: false };
    }
  }

  writeFileSync(path, generateWranglerToml(env), { encoding: 'utf-8', mode: 0o600 });
  return { path, created: true };
}

function isDirectExecution(): boolean {
  const entry = process.argv[1];
  return !!entry && resolve(entry) === fileURLToPath(import.meta.url);
}

if (isDirectExecution()) {
  const result = ensureCloudflareWranglerConfig(process.cwd(), process.env);
  console.log(result.created
    ? `Generated ignored Worker config: ${result.path}`
    : `Using existing Worker config: ${result.path}`);
}
